version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: socio-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mekke187
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: socio
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
